// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJGhXnhABaxLui_kZeJG49GVlN9iRVyi4',
    appId: '1:1075297360172:web:bc20aa9bc31b96e53c3489',
    messagingSenderId: '1075297360172',
    projectId: 'mamba-fitness-dev',
    authDomain: 'mamba-fitness-dev.firebaseapp.com',
    storageBucket: 'mamba-fitness-dev.appspot.com',
    measurementId: 'G-LMC57506WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWCBS1a-48hOlL8fdRwxeva7h3_NiBA7s',
    appId: '1:1075297360172:android:a1463f7fe9d8c6033c3489',
    messagingSenderId: '1075297360172',
    projectId: 'mamba-fitness-dev',
    storageBucket: 'mamba-fitness-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF8wjJw9jrwjUcgitbKHGP8KDL4qz1LoQ',
    appId: '1:1075297360172:ios:bf047898fe82d2b93c3489',
    messagingSenderId: '1075297360172',
    projectId: 'mamba-fitness-dev',
    storageBucket: 'mamba-fitness-dev.appspot.com',
    iosBundleId: 'com.mamba.mambaprofessionalapp.dev',
  );
}
