// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYFglgzIMLYXB9XQPaZ977MKUMseCJCvY',
    appId: '1:331547241606:web:0861373eba57dd997d3507',
    messagingSenderId: '331547241606',
    projectId: 'mamba-style',
    authDomain: 'mamba-style.firebaseapp.com',
    storageBucket: 'mamba-style.appspot.com',
    measurementId: 'G-J1CSKZLSZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnOl8HKFgrpvbGkFIgyZl9qB4tCOmJKSk',
    appId: '1:331547241606:android:3ae9fe3e0861fd0c7d3507',
    messagingSenderId: '331547241606',
    projectId: 'mamba-style',
    storageBucket: 'mamba-style.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu2cNcy52ifGK8rp3GYb7FiWV0EmpbFuc',
    appId: '1:331547241606:ios:f62bc6d192bad5e27d3507',
    messagingSenderId: '331547241606',
    projectId: 'mamba-style',
    storageBucket: 'mamba-style.appspot.com',
    androidClientId: '331547241606-16ebe70vk109mlsti2vros68l6lm3d3g.apps.googleusercontent.com',
    iosClientId: '331547241606-ebeqpaephnudpu4b2f37jt7d04ub387c.apps.googleusercontent.com',
    iosBundleId: 'com.mamba.mambaprofessionalapp',
  );
}
